(()=>{
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(u,o={})=>{const r=await fetch(u,{headers:{'Content-Type':'application/json'},...o});const d=await r.json();if(!r.ok)throw new Error(d.error||r.statusText);return d};
const PRESETS=[
 {id:'aitmpl',name:'AI Templates · Plugins',url:'https://www.aitmpl.com/plugins/',type:'text',interval_minutes:360,tag:'Plugin discovery'},
 {id:'awesome',name:'Awesome · Curated Index',url:'https://raw.githubusercontent.com/sindresorhus/awesome/main/readme.md',type:'text',interval_minutes:720,tag:'Open-source discovery'},
 {id:'frontend-design',name:'Claude Code · Frontend Design',url:'https://raw.githubusercontent.com/anthropics/claude-code/main/plugins/frontend-design/skills/frontend-design/SKILL.md',type:'text',interval_minutes:720,tag:'Design reference'}
];
function ensure(){const nav=document.querySelector('.support-nav');if(nav&&!$('dataHubNav')){const d=document.createElement('button');d.id='dataHubNav';d.className='nav-item';d.innerHTML='↻ <span>Data Hub</span>';nav.appendChild(d);d.onclick=openData;const m=document.createElement('button');m.id='mobileNav';m.className='nav-item';m.innerHTML='▤ <span>Mobile Runtime</span>';nav.appendChild(m);m.onclick=openMobile}
 if(!$('orchaHybridOverlay')){const w=document.createElement('div');w.id='orchaHybridOverlay';w.className='orcha-overlay';w.setAttribute('role','dialog');w.setAttribute('aria-modal','true');w.innerHTML=`<section class="orcha-hybrid-shell"><header><div><b id="hybridTitle">Orcha Hybrid</b><small id="hybridSub">Data Hub · Mobile Runtime</small></div><button id="hybridClose" class="hybrid-icon" aria-label="Đóng">×</button></header><main id="hybridBody"></main></section>`;document.body.appendChild(w);$('hybridClose').onclick=()=>closeOverlay();w.onclick=e=>{if(e.target===w)closeOverlay()}}
 if(!$('sourceDialog')){const d=document.createElement('dialog');d.id='sourceDialog';d.className='orcha-source-dialog';d.innerHTML=`<form method="dialog" id="sourceForm"><div class="source-dialog-head"><div><span class="eyebrow">DATA SOURCE</span><h2>Thêm nguồn dữ liệu</h2><p>Nguồn chỉ được đọc. Orcha không gửi POST/PUT/DELETE trong background sync.</p></div><button value="cancel" class="hybrid-icon" aria-label="Đóng">×</button></div><div class="preset-row" id="sourcePresets"></div><div class="source-form-grid"><label>Tên nguồn<input id="sourceName" required maxlength="120" placeholder="Ví dụ: Design references"></label><label>Loại<select id="sourceType"><option value="json">JSON API</option><option value="rss">RSS</option><option value="atom">Atom</option><option value="text">Text / Markdown / HTML</option></select></label><label class="wide">URL<input id="sourceUrl" required type="url" placeholder="https://..."></label><label>Chu kỳ cập nhật<input id="sourceInterval" type="number" min="15" value="60"></label><label>Trạng thái<select id="sourceEnabled"><option value="1">Bật tự đồng bộ</option><option value="0">Tạm dừng</option></select></label></div><div id="sourceFormError" class="form-error" role="alert"></div><footer><button value="cancel" class="btn secondary">Hủy</button><button id="saveSource" value="default" class="btn primary">Thêm nguồn</button></footer></form>`;document.body.appendChild(d);$('sourcePresets').innerHTML=PRESETS.map(x=>`<button type="button" data-preset="${x.id}"><b>${esc(x.name)}</b><small>${esc(x.tag)}</small></button>`).join('');$('sourcePresets').querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));$('sourceForm').onsubmit=saveSource}
}
function closeOverlay(){$('orchaHybridOverlay')?.classList.remove('show')}
function openSourceDialog(){ensure();$('sourceForm').reset();$('sourceInterval').value='60';$('sourceEnabled').value='1';$('sourceFormError').textContent='';$('sourceDialog').showModal();setTimeout(()=>$('sourceName').focus(),40)}
function applyPreset(id){const p=PRESETS.find(x=>x.id===id);if(!p)return;$('sourceName').value=p.name;$('sourceUrl').value=p.url;$('sourceType').value=p.type;$('sourceInterval').value=p.interval_minutes;$('sourceEnabled').value='1'}
async function saveSource(e){e.preventDefault();const btn=$('saveSource');const body={name:$('sourceName').value.trim(),url:$('sourceUrl').value.trim(),type:$('sourceType').value,interval_minutes:Number($('sourceInterval').value||60),enabled:$('sourceEnabled').value==='1'};if(!body.name||!/^https?:\/\//i.test(body.url)){return $('sourceFormError').textContent='Nhập tên nguồn và URL bắt đầu bằng http:// hoặc https://.'}btn.disabled=true;btn.textContent='Đang thêm…';try{await api('/api/data/sources',{method:'POST',body:JSON.stringify(body)});$('sourceDialog').close();await renderData()}catch(err){$('sourceFormError').textContent=err.message}finally{btn.disabled=false;btn.textContent='Thêm nguồn'}}
async function openData(){ensure();$('orchaHybridOverlay').classList.add('show');$('hybridTitle').textContent='Data Hub';$('hybridSub').textContent='Nguồn sống · tự cập nhật · local cache';await renderData()}
async function renderData(){const [rows,st]=await Promise.all([api('/api/data/sources'),api('/api/data/status')]);$('hybridBody').innerHTML=`<div class="hybrid-hero"><div><span class="eyebrow">LIVE KNOWLEDGE</span><h2>Dữ liệu không dừng ở local</h2><p>Kết nối nguồn tham khảo, API và feed; Orcha giữ cache local rồi đưa evidence liên quan vào Working Context.</p></div><div class="hybrid-actions"><button class="btn primary" id="addSource">+ Thêm nguồn</button><button class="btn secondary" id="syncAll">↻ Đồng bộ đến hạn</button></div></div><div class="hybrid-stats"><div><span>Nguồn</span><b>${st.sources}</b></div><div><span>Đang bật</span><b>${st.enabled}</b></div><div><span>Fetch guard</span><b>${st.policy.max_fetch_mb} MB</b></div><div><span>Lịch tối thiểu</span><b>${st.policy.min_interval_minutes} phút</b></div></div><div class="reference-strip"><div><b>Reference presets</b><small>Thêm nhanh nguồn nghiên cứu; Orcha chỉ lưu URL + dữ liệu cache, không nhập code/plugin.</small></div>${PRESETS.map(p=>`<button data-add-preset="${p.id}">${esc(p.name)}</button>`).join('')}</div><div class="source-grid">${rows.map(s=>{const x=st.state[s.id]||{};return `<article><div class="source-title"><div><b>${esc(s.name)}</b><small>${esc(s.type)} · mỗi ${s.interval_minutes} phút</small></div><span class="source-state ${s.enabled?'on':'off'}">${s.enabled?'ON':'PAUSED'}</span></div><p title="${esc(s.url)}">${esc(s.url)}</p><div class="source-meta"><span>${esc(x.status||'chưa sync')}</span><span>${x.documents??0} docs</span></div><div class="card-actions"><button data-sync="${esc(s.id)}">Sync ngay</button><button data-toggle="${esc(s.id)}" data-enabled="${s.enabled?'1':'0'}">${s.enabled?'Tạm dừng':'Bật'}</button></div></article>`}).join('')||'<div class="empty-source"><b>Chưa có nguồn ngoài</b><p>Dùng preset hoặc thêm API/RSS/Text để Orcha cập nhật knowledge theo lịch.</p></div>'}</div>`;
 $('addSource').onclick=openSourceDialog;$('syncAll').onclick=async()=>{await api('/api/data/sync',{method:'POST',body:'{}'});await renderData()};$('hybridBody').querySelectorAll('[data-add-preset]').forEach(b=>b.onclick=()=>{openSourceDialog();applyPreset(b.dataset.addPreset)});$('hybridBody').querySelectorAll('[data-sync]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/data/sync',{method:'POST',body:JSON.stringify({source_id:b.dataset.sync})});await renderData()}finally{b.disabled=false}});$('hybridBody').querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{await api(`/api/data/sources/${encodeURIComponent(b.dataset.toggle)}/enabled`,{method:'POST',body:JSON.stringify({enabled:b.dataset.enabled!=='1'})});await renderData()})}
async function openMobile(){ensure();$('orchaHybridOverlay').classList.add('show');$('hybridTitle').textContent='Mobile Runtime';$('hybridSub').textContent='Device-aware · privacy-aware · hybrid fallback';$('hybridBody').innerHTML=`<div class="hybrid-hero"><div><span class="eyebrow">MOBILE ROUTER</span><h2>Chạy đúng model cho đúng thiết bị</h2><p>Ưu tiên on-device; chỉ chuyển peer/remote khi chính sách privacy cho phép.</p></div></div><div class="mobile-form"><label>Thiết bị<select id="mobOS"><option value="ios">iOS / iPadOS</option><option value="android">Android</option></select></label><label>RAM GB<input id="mobRam" type="number" value="6" min="1"></label><label>Storage trống GB<input id="mobStorage" type="number" value="8" min="1"></label><label>Pin %<input id="mobBattery" type="number" value="80" min="0" max="100"></label><label>Privacy<select id="mobPrivacy"><option value="balanced">Balanced</option><option value="strict">Strict · không gửi ra ngoài</option></select></label><label class="wide">Tác vụ<input id="mobTask" value="Chat tiếng Việt và phân tích tài liệu"></label><button id="mobRecommend" class="btn primary wide">Chọn runtime tốt nhất</button></div><div id="mobileResult"></div>`;$('mobRecommend').onclick=recommendMobile;await recommendMobile()}
async function recommendMobile(){const body={device:{os:$('mobOS').value,ram_gb:Number($('mobRam').value),free_storage_gb:Number($('mobStorage').value),battery_percent:Number($('mobBattery').value),network:true},task:$('mobTask').value,privacy:$('mobPrivacy').value};const r=await api('/api/mobile/recommend',{method:'POST',body:JSON.stringify(body)});$('mobileResult').innerHTML=`<article class="mobile-result"><span class="eyebrow">${esc(r.mode)}</span><h3>${r.selected?esc(r.selected.name):'Không chạy model local lúc này'}</h3><p>Task: ${esc(r.task)} · budget ${r.device_budget_mb} MB</p><div class="runtime-path">${r.runtime_preference.map((x,i)=>`<span>${i+1}</span><b>${esc(x)}</b>`).join('')}</div><small>${esc(r.note)}</small></article>`}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('orchaHybridOverlay')?.classList.contains('show'))closeOverlay()});setTimeout(ensure,350);})();